name = "Polyuretanes"
uuid = "770902dd-bf43-47cf-89f4-4676401ab19a"
authors = ["Leandro Martinez <leandro@iqm.unicamp.br> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
